Checkpoint 5: Views
CRClothier/rails-blog pull request #5
Opened 2022-06-17 21:09 UTC by CRClothier

- Implement the design from the sneak peek wireframes.
- Use methods that you have created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).

2022-06-17 21:51 UTC, SajjadAhmad14 requested changes
## Required Changes ♻️
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hi Chris, 
 ### You have been doing a tremendous job so far :ok_hand:

## To Highlight 🎉
Git flow is followed. :heavy_check_mark:
README is professional. :heavy_check_mark:
## To Improve 🙏

- [ ] Please check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### Please remember to tag me in your question so I can receive the notification.
**_Note: Please do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-17 21:51 UTC, SajjadAhmad14 commented on app/views/users/index.html.erb
> +<% @users.each do |user| %>
Every user on `app/views/index.html.erb`should have a link and clicking on it should take the user to the user's show page.

2022-06-17 21:51 UTC, SajjadAhmad14 commented on app/views/users/show.html.erb
> +
There should be `See all Post` link that redirect the user to the user's post index.

2022-06-17 21:51 UTC, SajjadAhmad14 commented on app/controllers/posts_controller.rb
> +  def index
There is an error when the user tries to see the posts index page. Kindly see the screenshot below.
![posts](https://user-images.githubusercontent.com/35504149/174405273-622ef924-df2b-4520-bba7-3336e0579b09.png)

2022-06-17 21:51 UTC, SajjadAhmad14 commented on app/controllers/users_controller.rb
> +  def show
The user encounters this error when he tries to go to the user's show page.
![show](https://user-images.githubusercontent.com/35504149/174405581-80f5deb5-3b3e-42ac-8c5d-8270ad6b718b.png)

2022-06-30 04:42 UTC, merged

2022-06-30 04:43 UTC, CRClothier reviewed
yes